PROJECT=btracker
SUBPROJECTS=$(PROJECT)-service
VERSION?=commit_$(shell git rev-parse --short HEAD)
DOCKER_REPOSITORY=jvaltersson/btracker
export VERSION

build-only:
	docker-compose -f docker-compose.yml build

build: build-only tag

%-tag:
	docker tag $*:$(VERSION) $*:latest
	docker tag $*:$(VERSION) $(DOCKER_REPOSITORY)/$*:$(VERSION)
	docker tag $*:$(VERSION) $(DOCKER_REPOSITORY)/$*:latest

tag: $(SUBPROJECTS:%=%-tag)

unittest: clear-containers build
	docker-compose -f docker-compose.yml -f docker-compose.unittest.yml run --rm unittest

unittest-watch: clear-containers build
	docker-compose -f docker-compose.yml -f docker-compose.unittest.yml run --rm unittest-watch

run-local: build
	docker-compose -f docker-compose.yml run -p 3000:3000 $(PROJECT) run-local

run-deploy: build
	docker-compose -f docker-compose.yml run -p 3000:3000 $(PROJECT) run-deploy

migrate: build clear-containers
	docker-compose run \
		--rm \
		btracker \
		alembic upgrade head

generate-migration: migrate
	docker-compose run \
		--rm \
		--entrypoint alembic \
		btracker \
		revision --autogenerate -m "autogenerated migration"

clear-containers: kill-containers
	docker-compose -f docker-compose.yml -f docker-compose.unittest.yml rm --force

kill-containers:
	docker-compose -f docker-compose.yml -f docker-compose.unittest.yml kill
